# Generated by Django 5.0.1 on 2024-01-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketForecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mydata',
            table='OUTPUT',
        ),
    ]
